"""End-to-end PR video orchestration: select clips, narrate, render, post."""
from __future__ import annotations

import logging
from pathlib import Path

from datetime import datetime, timezone
from pathlib import Path

from trace_cli.contribution_map.mapper import classify, render_comment
from trace_cli.contribution_map.scanner import collect_agent_edits
from trace_cli.github.client import GitHubClient, validate_pr_url
from trace_cli.pr_video.narration import build_per_clip_scripts
from trace_cli.pr_video.render import RenderResult, render
from trace_cli.pr_video.selector import InsufficientContent, select_clips
from trace_cli.session.models import Transcript
from trace_cli.session.store import SessionStore
from trace_cli.timeline.builder import from_json as timeline_from_json
from trace_cli.videodb.client import VideoDBClient

log = logging.getLogger("trace.pr_video.generator")


COMMENT_TEMPLATE = (
    "## trace walkthrough\n\n"
    "Auto-generated narrated video covering the session that produced this PR.\n\n"
    "{preview_md}"
    "**Watch with narration:** {url}\n\n"
    "_Stitched from {n} clips totaling {dur:.0f}s. Narration generated by VideoDB._\n"
    "_Built with [trace](https://github.com/) - VideoDB hackathon entry._"
)


def generate_pr_video(session_id: str, pr_url: str, *, dry_run: bool = False) -> RenderResult:
    """Full PR video pipeline; posts a comment unless dry_run."""
    pr = validate_pr_url(pr_url)
    store = SessionStore()
    meta = store.read_metadata(session_id)
    if not meta.video_id:
        raise RuntimeError(
            f"session {session_id} has no video_id; run `trace stop` indexing first"
        )

    # Load timeline + transcript
    tl_path = store.timeline_path(session_id)
    if not tl_path.exists():
        raise RuntimeError(f"timeline.json missing: {tl_path}")
    timeline = timeline_from_json(tl_path.read_text(encoding="utf-8"))

    tr_path = store.transcript_path(session_id)
    transcript = Transcript(session_id=session_id, segments=[])
    if tr_path.exists():
        try:
            transcript = Transcript.model_validate_json(tr_path.read_text(encoding="utf-8"))
        except Exception as e:  # noqa: BLE001
            log.warning("transcript parse failed: %s", e)

    # Fetch diff
    gh = GitHubClient()
    files = gh.get_pr_files(pr_url)
    diff_paths = [f["path"] for f in files]
    log.info("PR diff has %d files: %s", len(diff_paths), diff_paths[:10])

    # Select clips
    clips = select_clips(timeline, diff_paths)
    log.info("selected %d clips totaling %.1fs", len(clips), sum(c.duration for c in clips))

    # Per-clip narration grounded in scene index
    client = VideoDBClient()
    pr_title = f"PR #{pr.number}"
    pr_summary = ", ".join(f"{f['path']} (+{f['additions']} -{f['deletions']})" for f in files[:5])
    scenes: list[dict] = []
    scene_index_id = meta.model_dump().get("scene_index_id")
    if scene_index_id and meta.video_id:
        try:
            video = client.get_video(meta.video_id)
            scenes = client.get_scenes(video, scene_index_id)
            log.info("scenes for narration: %d windows", len(scenes))
        except Exception as e:  # noqa: BLE001
            log.warning("scene fetch failed (%s); narration without visual context", e)
    scripts = build_per_clip_scripts(
        client, clips, transcript,
        pr_title=pr_title, pr_summary=pr_summary,
        scenes=scenes,
    )
    log.info("narration: %d chunks, total %d chars", len(scripts), sum(len(s) for s in scripts))

    # Render + assemble Timeline with per-clip overlays
    result = render(client, meta.video_id, clips, scripts, pr_title=pr_title)
    log.info("PR video HLS URL: %s", result.hls_url)

    # Stop sandbox now that voice generation is done — saves credits.
    try:
        client.stop_sandbox()
    except Exception:  # noqa: BLE001
        pass

    # Persist artifacts
    store.artifact_path(session_id, "narration.txt").write_text(result.narration_text, encoding="utf-8")
    store.artifact_path(session_id, "pr_video_url.txt").write_text(result.hls_url, encoding="utf-8")
    store.link_pr(pr_url, session_id)

    if dry_run:
        return result

    # Render thumbnail + upload as release asset for clickable embed in PR body.
    preview_thumb_url: str | None = None
    try:
        from trace_cli.pr_video.preview import render_thumbnail, upload_image_as_release_asset
        thumb_path = store.artifact_path(session_id, "pr_thumbnail.jpg")
        if render_thumbnail(result.hls_url, out_path=thumb_path, at_seconds=min(5.0, result.total_seconds / 2)):
            preview_thumb_url = upload_image_as_release_asset(
                thumb_path,
                owner=pr.owner,
                repo=pr.repo,
                tag="trace-previews",
                content_type="image/jpeg",
            )
    except Exception as e:  # noqa: BLE001
        log.warning("thumbnail step failed: %s", e)

    # Post contribution map comment
    map_url: str | None = None
    if meta.project_dir:
        try:
            from trace_cli.contribution_map.scanner import _all_saved_files
            agent_edits = collect_agent_edits(
                Path(meta.project_dir),
                started_at=meta.started_at,
                stopped_at=meta.stopped_at or datetime.now(timezone.utc),
                timeline=timeline,
                transcript=transcript,
                scenes=scenes,
            )
            saved = _all_saved_files(
                Path(meta.project_dir),
                started_at=meta.started_at,
                stopped_at=meta.stopped_at or datetime.now(timezone.utc),
            )
            contributions = classify(files, agent_edits, saved_files=saved)
            map_body = render_comment(contributions)
            map_url = gh.post_comment(pr_url, map_body)
            log.info("posted contribution map: %s", map_url)
            store.artifact_path(session_id, "contribution_map.md").write_text(map_body, encoding="utf-8")
        except Exception as e:  # noqa: BLE001
            log.warning("contribution map failed: %s", e)

    # Append PR description (preview thumbnail + What/Why/Struggles/Follow-ups)
    try:
        from trace_cli.pr_description.generator import build as build_description
        full_session_url = None
        try:
            full_video = client.get_video(meta.video_id)
            full_session_url = full_video.generate_stream()
        except Exception as e:  # noqa: BLE001
            log.warning("full session stream URL failed: %s", e)
        desc = build_description(
            client, files, transcript, timeline,
            pr_title=f"PR #{pr.number}",
            video_url=result.hls_url,
            contribution_url=map_url,
            preview_thumb_url=preview_thumb_url,
            pr_ref=pr,
            full_session_url=full_session_url,
        )
        gh.set_description(pr_url, desc.body)
        store.artifact_path(session_id, "pr_description.md").write_text(desc.body, encoding="utf-8")
        log.info("appended PR description (%d chars)", len(desc.body))
    except Exception as e:  # noqa: BLE001
        log.warning("PR description append failed: %s", e)

    # Focus Mode: post a per-file review checklist comment
    try:
        from trace_cli.focus_mode.builder import build_focus, render_comment as render_focus
        focus_entries = build_focus(files, timeline, transcript)
        focus_body = render_focus(focus_entries)
        gh.post_comment(pr_url, focus_body)
        store.artifact_path(session_id, "focus_mode.md").write_text(focus_body, encoding="utf-8")
        log.info("posted focus mode comment (%d entries)", len(focus_entries))
    except Exception as e:  # noqa: BLE001
        log.warning("focus mode post failed: %s", e)

    return result
